language : java

dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - "psql -c 'create database hrp;' -U postgres"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"